# Generated by Django 4.2.5 on 2023-09-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="author", name="slug",),
        migrations.RemoveField(model_name="books", name="slug",),
        migrations.RemoveField(model_name="condition", name="slug",),
        migrations.RemoveField(model_name="genre", name="slug",),
    ]
