# Generated by Django 4.2.5 on 2023-09-29 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0002_remove_author_slug_remove_books_slug_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Books", new_name="Book",),
        migrations.AlterModelOptions(name="book", options={},),
    ]
