# Generated by Django 4.2.5 on 2023-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_rename_books_book_alter_book_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="author", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book", name="condition", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book", name="genre", field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Condition",),
        migrations.DeleteModel(name="Genre",),
    ]
