# Generated by Django 4.2.5 on 2023-09-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_author_alter_book_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book", name="pages", field=models.IntegerField(blank=True),
        ),
    ]
