# Generated by Django 4.2.5 on 2023-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_condition_slug_genre_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
