# Generated by Django 4.2.5 on 2023-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_alter_book_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
